language: nix
sudo: false

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work

matrix:
  fast_finish: true
  include:
    # Add build targets here
    - env: GHCVER=8.0.2 CACHE_NAME=8.0.2
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [ghc-8.0.2], sources: [hvr-ghc]}}

    - env: GHCVER=8.2.1 CACHE_NAME=8.2.1 BUILD_BINARY=1
      compiler: ": #stack 8.2.1"
      addons: {apt: {packages: [ghc-8.2.1], sources: [hvr-ghc]}}

    - env: GHCVER=8.2.1 CACHE_NAME=8.2.1-osx BUILD_BINARY=1
      os: osx
      compiler: ": #stack 8.2.1"
      addons: {apt: {packages: [ghc-8.2.1], sources: [hvr-ghc]}}

install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ./.travis/install-stack.sh
 - stack build --test --bench --no-run-tests --no-run-benchmarks --ghc-options="$GHC_OPTIONS" --copy-bins --local-bin-path $HOME

script:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - |
   set -ex
   # Run tests
   stack --no-terminal test --ghc-options="$GHC_OPTIONS"
   set +ex

deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      branch: travis-release-binary-automation
    file_glob: true
    file: $HOME/fission-cli-*
    api_key:
      secure: XKMKM4KQPGqqCG8+ue8fi8GCp9h9nJTsClTjaNq4vnpKQkV3TMJI2QUUCmVXbkV+yD9ysthlUj5KORr15x9UARLqUtVvbijbjxMCmvIH4XupYZeowrotHL7g56T4N6VJRJhyCCTinkNK+FqrjrChBoqaN7V9qtKIwAAYituux/+k/s4yZDiuBqecbOKSL7fJ8LQoWq+9mhyXMtPN1vasqWXQNn1pKobdRrWFLx1BkA4XrULgHUPVRi4SKxH3092Xa1I/dudxyrKfiAENYUqH9T8owgGe6BX6ugvQ5oL6y26KyiIymx8VaOEuLJ0ONI84pUUkABuHAEz9zfTWtSMKx3t3tEfHthvgjZjsFKEze1UHpbF5WWDLsTuer+fErViLfYlimFssDwyKIbfgHRAVkslj4SCbEGT1PN0vG4pCHXuxBVbbsL4oTgy6Ik2/sfbFeMxNIGPxighApGy9YiFys6dXz1fNOh9RqhQQUl9qW+nW1/rxS2HAVq3XL9h/6w0Kwgx6NlMmfQSb5m8ty/+QxBaX6C+Izpb8L6TWzEbZz8wMTBpbG5ZjpY1+KS5y0snmNkwicAS5Y54ZIVB+hhnI2B/Vtq4QeqchCavm6+R+X38tn189cApWofzZlXZRCmXuJ/VKY3Hg74SZKkSspnwxYngV/MNxIEmCO+K0CdS0t6w=
